"""Add massages model

Revision ID: e8b3d860bcf9
Revises: 334ce45ec451
Create Date: 2023-12-16 16:34:16.910248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8b3d860bcf9'
down_revision: Union[str, None] = '334ce45ec451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_recipient', sa.Integer(), nullable=True),
    sa.Column('send_at', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('id_sender', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('user', 'friend_age_from',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'friend_age_to',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'friend_age_to',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'friend_age_from',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('messages')
    # ### end Alembic commands ###
