"""Add massages model +id_sender

Revision ID: bb69fe6d6aa6
Revises: e8b3d860bcf9
Create Date: 2023-12-16 16:40:39.321382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb69fe6d6aa6'
down_revision: Union[str, None] = 'e8b3d860bcf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('id_sender', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'id_sender')
    # ### end Alembic commands ###
