version: "3.7"
services:
  db:
    image: postgres:15
    container_name: db_app
    command: -p 5432
    expose:
      - 5432
    env_file:
      - ../.env

  redis:
    image: redis:7
    container_name: redis_app

  app:
    build:
      context: ..
    env_file:
      - ../.env
    container_name: fastapi_app
    ports:
      - 9999:8000
    depends_on:
      - db
      - redis
